AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "wolfeidau: Security Transform"

Parameters:
  AppName:
    Description: Provide the name of the application.
    Type: String
    Default: "cf-security-transform"
  Stage:
    Description: Provide the stage of the application.
    Type: String
    Default: "dev"
  Branch:
    Description: Provide the branch of the application.
    Type: String
    Default: "master"

Globals:
  Function:
    Runtime: go1.x
    Timeout: 30
    MemorySize: 256
    Environment:
      Variables:
        APP_NAME: !Ref AppName
        STAGE: !Ref Stage
        BRANCH: !Ref Branch

Resources:
  SecurityTransformFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: transform-lambda
      CodeUri: ../../handler.zip
  SecurityTransformFunctionPermissions:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt SecurityTransformFunction.Arn
      Principal: 'cloudformation.amazonaws.com'
  SecurityTransform:
    Type: AWS::CloudFormation::Transform
    Properties:
      Name: !Sub '${AWS::AccountId}::SecurityTransform'
      Description: Create Security transforms
      RoutingTable:
        '*': 0_1
      Versions:
        - VersionName: 0_1
          Description: Version 0_1 of the Security transform
          FunctionName: !GetAtt SecurityTransformFunction.Arn
Outputs:
  AppName:
    Value: !Ref AppName
  Stage:
    Value: !Ref Stage
  Branch:
    Value: !Ref Branch